[project]
name="causal_discovery_replication"
requires-python=">=3.12"
dependencies = [
    "causal_testing_framework @ git+https://github.com/CITCOM-project/CausalTestingFramework@22429e6dd7463ce65a7563fc9fdaf4c1df4b7998",
    "pgmpy>=1.1.2",
]
dynamic=["version"]

[tool.black]
# https://github.com/psf/black
line-length = 120
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 120
